### ISSUE TITLE
Missing libreoffice.Jar  in  "Setup Eclipse for development"

### ISSUE THREAD

**Issue by michaelmassee** [LibreOffice/loeclipse#100]
Hi,
in  the Doku  for setting up in Eclipse the  library named LO-Classes,  the Line 
"Add the LibreOffice jars **unoil.jar juh.jar jurt.jar ridl.jar unoloader.jar.** You find them here:" 
is missing **libreoffice.Jar**

**Comment by michaelmassee** [comment]
only these **libreoffice.jar unoil.jar** are requered  ?

what about  juh.jar jurt.jar ridl.jar unoloader.jar ?

**Comment by smehrbrodt** [comment]
They have been merged into libreoffice.jar, see https://wiki.documentfoundation.org/ReleaseNotes/7.0#Java_support
