### ISSUE TITLE
v4.0.2 LibreOffice LOEclipse 

### ISSUE THREAD

**Issue by MedoHamdani** [LibreOffice/loeclipse#115]
Could not find jar:file:/C:/Users/medoh/Downloads/loeclipse-4.0.2.zip!/

Could not install LO Plugin

Eclipse didn't recognize it.

**Comment by MedoHamdani** [comment]
https://www.perplexity.ai/search/would-like-to-build-an-extensi-nWE659ZIQbScJks_rDCDxQ

**Comment by smehrbrodt** [comment]
Please follow the instructions in the README to install.
