### ISSUE TITLE
Be able to use Ant to build oxt from a Python project only

### ISSUE THREAD

**Issue by prrvchr** [LibreOffice/loeclipse#119]
Hi all,

I just noticed that it would be possible to use Ant to build the oxt file even if the project is only a Python project and not Java.

And since I use LOEclipse for many Python projects I would like to offer the ability to build the project from the command line.

To do this it seems to me that there are only two things to do:
- List the Python and Java projects in the **Project to build Script** list
- Modify the build.xml.tpl file to take into account when the project is not Java

Do you think this is feasible and if so, how do you know in Ant if the project is Python, Java or Python and Java?

Thanks.

**Comment by smehrbrodt** [comment]
Sure that's a good idea.
The python port is still incomplete in many places, this is one of them.

> Do you think this is feasible and if so, how do you know in Ant if the project is Python, Java or Python and Java?

Sure it's feasible. I would probably just duplicate the `build.xml.tpl` file, adjust it for Python and then choose either `build.java.xml.tpl` or `build.python.xml.tpl` as template depending on the project nature.
