### ISSUE TITLE
Extension fails to deploy

### ISSUE THREAD

**Issue by xbubli** [LibreOffice/loeclipse#12]
I've pointed loeclipse to SDK and a program directory of my development build. I've created a 'LibreOffice application' run configuration. 

However, 'Run' only starts a LibreOffice instance, doesn't really deploy the extension from my project. It doesn't even print any error message anywhere, it just fails silently. Deploying via unopkg from command line, as well as from GUI extension manager works flawlessly.

**Comment by smehrbrodt** [comment]
Can you please leave your OS, LibreOffice and Eclipse version so I can try to reproduce this?

**Comment by smehrbrodt** [comment]
Closing b/c no feedback. Please reopen once you have the information at hand.

**Comment by smehrbrodt** [comment]
This probably is the same as #55, should hopefully be fixed now with v2.2.4.
