### ISSUE TITLE
LibreOffice Starter Extension

### ISSUE THREAD

**Issue by josafasdr** [LibreOffice/loeclipse#16]
Hi.

The LibreOffice Starter Extension is not adding anything to Writer.
I'm following the step-by-step. What is the problem?

**Comment by smehrbrodt** [comment]
Does the extension show up in Tools->Extension Manager?

**Comment by josafasdr** [comment]
No, but I added manually from the **dist** folder. It's right?

**Comment by smehrbrodt** [comment]
If it doesn't show up in the Extension Manager it's not installed.
You can either add it manually from the dist folder or use the Eclipse Run Configuration as described in the howto.

**Comment by josafasdr** [comment]
Thanks!
