### ISSUE TITLE
RegistrationHandler.classes sometimes empty

### ISSUE THREAD

**Issue by smehrbrodt** [LibreOffice/loeclipse#21]
It happened to me a few times that RegistrationHandler.classes was emptied.
The generated extension then no longer works.

Need to investigate this.

**Comment by smehrbrodt** [comment]
At least we should show an error message when this file is empty.

**Comment by Mianto** [comment]
#48 When RegistrationHandler.class is missing it shows an error message.Please check my code and give any further suggestion.
