### ISSUE TITLE
jodconnector.jar (missing)

### ISSUE THREAD

**Issue by Sirila** [LibreOffice/loeclipse#32]
When creating a Java UNO Client Application the jodconnector.jar in the Libraries tab is shown as missing.

**Comment by smehrbrodt** [comment]
This works for me, at least on Linux with latest Eclipse & LOEclipse.
Which OS, Eclipse, LOEclipse version do you have?

**Comment by Sirila** [comment]
OS: Linux Ubuntu 14.04 x86_64
Eclipse Version: Neon Release (4.6.0), Build id: 20160613-1800
LOEclipse: 2.1.1
LibreOffice 5.1, LibreOffice SDK 5.1.4.2 64 bit
Java: JavaSE-1.8 64bit
https://www.anony.ws/image/Jllr

**Comment by smehrbrodt** [comment]
Thanks!
Does the jodconnector.jar show up in the project folder?

**Comment by Sirila** [comment]
No, there are only the .classpath file, the .project file and the project directory structure in it.

**Comment by smehrbrodt** [comment]
Can reproduce this.

**Comment by smehrbrodt** [comment]
Just released 2.1.3 (available on the update site).
Hope this fixes the problem.
