### ISSUE TITLE
Remove java version selector from extension wizard

### ISSUE THREAD

**Issue by smehrbrodt** [LibreOffice/loeclipse#43]
When generating an extension, you can select which java version is to be used for generating the extension skeleton.
As Java 5 is the only choice here, this should be removed.

![java selection](https://cloud.githubusercontent.com/assets/3502738/20967259/c2f8cf9c-bc7e-11e6-9ec6-bdcb97a7f639.png)

**Comment by akkisna** [comment]
Entire configuration page should be removed?

**Comment by smehrbrodt** [comment]
No, only the version selector
