### ISSUE TITLE
 Invalid LibreOffice path MacOs

### ISSUE THREAD

**Issue by kozla13** [LibreOffice/loeclipse#45]
Can someone help with this problem.

http://stackoverflow.com/questions/41257340/loeclipse-plugin-invalid-libreoffice-path-macos

**Comment by smehrbrodt** [comment]
Hi, thanks for the report. Unfortunately I have no Mac to test it.
Do you want to fix it? I can give you code pointers then.

**Comment by kozla13** [comment]
@smehrbrodt 
i can try.

**Comment by smehrbrodt** [comment]
Start looking here: https://github.com/LibreOffice/loeclipse/blob/023c2f11966aeaebfe32898fc2f43f98eb87624f/core/source/org/libreoffice/ide/eclipse/core/gui/OOoTable.java#L435

That's where the exception is thrown. Somewhere in OOo.java or AbstractOOo.java the checks are done.

**Comment by smehrbrodt** [comment]
For build instructions, see the readme, or ask me if anything is unclear.

**Comment by kozla13** [comment]
ok, thanks
