### ISSUE TITLE
Eclipse doesn't let me install loeclipse

### ISSUE THREAD

**Issue by Grosskopf** [LibreOffice/loeclipse#86]
Hi, so I tried to install loeclipse today through the Eclipse Marketplace.

It lets me select the parts I want to install, and then when I confirm that, it tells me this:

No repository found at http://eclipse-plugins.libreoffice.org.

of course there is no repository there since that is an http page and the page has a strict forward to https, is this really the issue? how can I install the plugin otherwise?

**Comment by smehrbrodt** [comment]
I changed the marketplace listing to point to https://eclipse-plugins.libreoffice.org meanwhile.
